[package]
name = "vscode_docs"
version = "0.0.0"
edition = "2024"
license = "MIT"
publish = false

[[bin]]
name = "vscode_docs"
test = false
doctest = false

[dependencies]
cow-utils = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
